# Generated by Django 3.2 on 2022-08-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220825_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slidelistimages',
            options={'verbose_name_plural': 'Slide-list Images'},
        ),
    ]
